### ISSUE TITLE
'electrum-dash-server start' does not work

### ISSUE THREAD

**Issue by santzi** [dashpay/electrum-dash-server#10]
Hi,

When I try to start Electrum server using 'electrum-dash-server start' -command, error occurs every time.
'electrum-dash-server stop' -command working ok.
I had to use 'run_electrum_dash_server' -command to start server, but this does not log the events to specified log -file.

Same error occurred, when I using:
"nohup run_electrum_dash_server > /dev/null 2>>/var/log/electrum-dash.log &".

"run_electrum_dash_server" working ok and also
"./run_electrum_dash_server >>/var/log/electrum-dash.log 2>&1" -command.
But when I using the latest command, I couldn't get it background.

OS:
Debian 8.5.0
3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux

I don't know how to fix this error.
error prints:

Traceback (most recent call last):
  File "/home/jeppa/Downloads/git/electrum-dash-server/run_electrum_dash_server", line 307, in <module>
    start_server(config)
  File "/home/jeppa/Downloads/git/electrum-dash-server/run_electrum_dash_server", line 234, in start_server
    setup_network_params(config)
  File "/home/jeppa/Downloads/git/electrum-dash-server/run_electrum_dash_server", line 73, in setup_network_params
    utils.PUBKEY_ADDRESS = int(params.get('pubkey_address'))
AttributeError: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/local/bin/run_electrum_dash_server", line 4, in <module>
    **import**('pkg_resources').run_script('electrum-dash-server==1.0', 'run_electrum_dash_server')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 534, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/electrum_dash_server-1.0-py2.7.egg/EGG-INFO/scripts/run_electrum_dash_server", line 307, in <module>

  File "/usr/local/lib/python2.7/dist-packages/electrum_dash_server-1.0-py2.7.egg/EGG-INFO/scripts/run_electrum_dash_server", line 234, in start_server

  File "/usr/local/lib/python2.7/dist-packages/electrum_dash_server-1.0-py2.7.egg/EGG-INFO/scripts/run_electrum_dash_server", line 73, in setup_network_params

AttributeError: 'NoneType' object has no attribute 'get'

**Comment by thelazier** [comment]
Are there any special modification in config file ?

**Comment by santzi** [comment]
This is my current config file

[server]
#username for running the daemon
username = yyyyyy
#hostname. set it to a FQDN in order to be reached from outside
host = 192.168.1.33
#ports
electrum_rpc_port = 8010
stratum_tcp_port = 50007
stratum_tcp_ssl_port = 50008
report_host = electrum-dash.us.to
report_stratum_tcp_port = 50007
report_stratum_tcp_ssl_port = 50008
banner = Welcome to DASH Electrum!
banner_file = /etc/electrum-dash.banner
irc = yes
irc_nick = santziDa
#IRC prefix for mainnet is "D_" and testnet is "d_"
irc_prefix = D_
ssl_certfile = /etc/ele_certs/server.crt
ssl_keyfile = /etc/ele_certs/server.key
logfile = /var/log/electrum-dash.log
donation_address =
max_subscriptions = 500

[leveldb]
#100 prune
pruning_limit = 100
path = /ele_db/dash/electrum-leveldb-utxo-100
#path = /dev/shm/dash

utxo_cache = 32000000
hist_cache = 64000000
addr_cache = 8000000

[dashd]
dashd_host = localhost
dashd_port = 9998
#user and password from dash.conf
dashd_user = xxxxxxx
dashd_password = xxxxxxx

**Comment by thelazier** [comment]
Your config look nice. 
try add 3 lines at the bottom

[network]
type = dash_main

**Comment by santzi** [comment]
I added these lines, but these does not effect. Same error occurs still.

**Comment by thelazier** [comment]
Is file 'src/networks.py' exists ?
Try re-pull the source from github?
Try re-run "python setup.py install" ?

BTW, I really have no idea if above trying doesn't help.
good luck :)

**Comment by thelazier** [comment]
@santzi , I guess  your server is currently online (D_santziDa), shall you give us some update on this issue ? 
Thanks :smile:

**Comment by santzi** [comment]
Yes, it's online, but this 'electrum-dash-server start' feature does not work. I have started it other way. Other Electrum servers (BTC and LTC) working fine, but this Dash Electrum doesn't.
I had this same error also with Linux Mint 17.1 Rebecca.

**Comment by santzi** [comment]
I will close this issue. No valid anymore.
