### ISSUE TITLE
blockchain_processor.py line 126, in dashd raise BaseException(r['error'])

### ISSUE THREAD

**Issue by santzi** [dashpay/electrum-dash-server#9]
Hi,
I'd like set up Electrum Dash server, but I have a strange problem now.
This is worked earlier like a charm, but then I had Linux Mint and little bit older Elertrum server version and dash core daemon.
Now I have Debian 8.5.0 (3.16.0-4-amd64), latest Dash core daemon and electrum-dash-server.
Dash Core Daemon version v0.12.0.58 (not compiled myself, binary downloaded from github)
Daemon working fine, but electrum server not when all block are pruned. I have started pruning from scratch, but not working.

I got always this error (all settings should be ok):

INFO:electrum-dash:catch_up: block 509150 (0.484s 18.325s) dbe3b3c51c45bf88100f07b6cf9109d95ceccc1b98c4695856294db02f554ea0
INFO:electrum-dash:catch_up: block 509200 (0.508s 12.740s) 35d2c2098b23ead375f62c5b2791e69036eebddb4d75efda0ed763c10c8fd5e8
INFO:electrum-dash:catch_up: block 509250 (0.402s 13.524s) b23121156331613836679df5658a6fdeef7e39d99f06c3e499134c4a57301862
INFO:electrum-dash:Blockchain is up to date.
INFO:electrum-dash:Memory pool initialized.
INFO:electrum-dash:blockchain: 509254 (0.003s)
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/home/jeppa/Downloads/git/electrum-dash-server/src/blockchain_processor.py", line 86, in do_catch_up
    self.main_iteration()
  File "/home/jeppa/Downloads/git/electrum-dash-server/src/blockchain_processor.py", line 923, in main_iteration
    proposals_status = self.get_proposals_status()
  File "/home/jeppa/Downloads/git/electrum-dash-server/src/blockchain_processor.py", line 359, in get_proposals_status
    return self.dashd('mnbudget', ['list'])
  File "/home/jeppa/Downloads/git/electrum-dash-server/src/blockchain_processor.py", line 126, in dashd
    raise BaseException(r['error'])
BaseException: {u'message': u'mnbudget "command"... ( "passphrase" )\nVote or show current budgets\n\nAvailable commands:\n  prepare            - Prepare proposal for network by signing and creating tx\n  submit             - Submit proposal for network\n  vote-many          - Vote on a Dash initiative\n  vote-alias         - Vote on a Dash initiative\n  vote               - Vote on a Dash initiative/budget\n  getvotes           - Show current masternode budgets\n  getinfo            - Show current masternode budgets\n  show               - Show all budgets\n  projection         - Show the projection of which proposals will be paid the next cycle\n  check              - Scan proposals and remove invalid\n  nextblock          - Get next superblock for budget system\n', u'code': -1}

I check "blockchain_processor.py", line 126" and it raised exception there.

```
    r = loads(respdata)
    if r['error'] is not None:
        raise BaseException(r['error'])
    return r.get('result')
```

"respdata" is very strange and that's why exception raised

**Comment by thelazier** [comment]
BTW, https://github.com/thelazier/electrum-dash-db might worth checking out to faster the synchronization time with mainnet.

**Comment by schinzelh** [comment]
I have sync the dashpay repo with @thelazier 's repos now

**Comment by santzi** [comment]
Now the electrum server working ok. Thank you very much. This ticket could be closed now.
